version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout:
          path: ~/ITKPerformanceBenchmarking
      - run:
          name: Build Docker testing image
          command: |
            docker pull insighttoolkit/performancebenchmarking-test:latest
            ~/ITKPerformanceBenchmarking/test/Docker/build.sh --cache-from=debian:9,insighttoolkit/performancebenchmarking-test:latest
      - run:
          name: Build and test
          command: |
            ~/ITKPerformanceBenchmarking/test/Docker/run.sh
      - deploy:
          name: Deploy Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push insighttoolkit/performancebenchmarking-test:latest
            fi
